services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true
    bind:
      $casUrl: '%pumukit_security.cas_url%'
      $casPort: '%pumukit_security.cas_port%'
      $casUri: '%pumukit_security.cas_uri%'
      $casAllowedIpClients: '%pumukit_security.cas_allowed_ip_clients%'
      $env: '%kernel.environment%'
      $cacheDir: '%kernel.cache_dir%'
      $casIdKey: '%pumukit_security.cas_id_key%'
      $casMailKey: '%pumukit_security.cas_mail_key%'
      $casGivenNameKey: '%pumukit_security.cas_givenname_key%'
      $casSurnameKey: '%pumukit_security.cas_surname_key%'
      $casGroupKey: '%pumukit_security.cas_group_key%'
      $casOriginKey: '%pumukit_security.cas_origin_key%'
      $createUsers: '%pumukit_security.create_users%'
      $profileMapping: '%pumukit_security.profile_mapping%'
      $permissionProfilesAttribute: '%pumukit_security.permission_profiles_attribute%'
      $defaultPermissionProfile: '%pumukit_security.default_permission_profile%'
      $forceOverridePermissionProfile: '%pumukit_security.force_override_permission_profile%'

  Pumukit\CasBundle\Services\CASService:
    class: Pumukit\CasBundle\Services\CASService

  Pumukit\CasBundle\Authentication\Provider\PumukitProvider:
    class: Pumukit\CasBundle\Authentication\Provider\PumukitProvider
    public: false

  Pumukit\CasBundle\Handler\LogoutSuccessHandler:
    class: Pumukit\CasBundle\Handler\LogoutSuccessHandler

  Pumukit\CasBundle\Services\CASUserService:
    class: Pumukit\CasBundle\Services\CASUserService
